{% set name = "pywatershed" %}
{% set version = "1.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pywatershed-{{ version }}.tar.gz
  sha256: 65c9bab1a715366895251850c25789562bb11f4d044006b00e53d4f667b8f9fe

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.9,<3.11
    - setuptools >=61
    - numpy
    - pip
  run:
    - python >=3.9,<3.11
    - numpy >=1.15.0
    - matplotlib-base >=1.4.0
    - netcdf4
    - networkx
    - numba
    - pandas >=1.4.0
    - pint
    - pyyaml
    - tqdm
    - xarray >=2023.5.0
    - xmltodict
    - epiweeks4cf


test:
  imports:
    - pywatershed
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/EC-USGS/pywatershed
  summary: pywatershed is a Python package for hydrologic modeling
  license: CC0-1.0
  license_file: LICENSE
  doc_url: https://pywatershed.readthedocs.io
  dev_url: https://github.com/EC-USGS/pywatershed

extra:
  recipe-maintainers:
    - jmccreight
    - jdhughes-usgs
    - wpbonelli
