{% set name = "pywatershed" %}
{% set version = "2.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pywatershed-{{ version }}.tar.gz
  sha256: 16d905f5a494560db3547b2c27cd9cd60bfe00ef8d1c742e0fd00c233bb0a656

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python 3.10
    - setuptools <=72.2.0
    - importlib_metadata <=7.0.1
    - numpy <2.0
    - twine <5.0.0
    - pip
  run:
    - cartopy
    - click !=8.1.0
    - dataretrieval
    - contextily
    - epiweeks
    - filelock
    - flopy
    - folium
    - geopandas
    - geoviews
    - git
    - holoviews
    - hvplot
    - ipython
    - ipywidgets
    - jupyter
    - jupyterlab
    - nbconvert
    - netCDF4
    - networkx
    - numpy >=2.0.0
    - numba
    - modflow-devtools
    - pandas >=1.4.0
    - pint
    - pip
    - pre-commit
    - pydot
    - pytest !=8.1.0
    - pytest-cov
    - pytest-env
    - pytest-order
    - pytest-xdist
    - python <3.12,>=3.10
    - pyyaml
    - ruff
    - shapely
    - sphinx
    - sphinx-book-theme >=0.3.3
    - sphinx-autodoc-typehints >=2.2.1
    - sphinx-autosummary-accessors
    - sphinx-copybutton
    - tqdm
    - xarray >=2024.06.0

test:
  imports:
    - pywatershed
  commands:
    - pip check
  requires:
    - python 3.10
    - pip

about:
  home: https://github.com/EC-USGS/pywatershed
  summary: pywatershed is a Python package for hydrologic modeling
  license: CC0-1.0
  license_file: LICENSE
  doc_url: https://pywatershed.readthedocs.io
  dev_url: https://github.com/EC-USGS/pywatershed

extra:
  recipe-maintainers:
    - jmccreight
    - jdhughes-usgs
    - wpbonelli
