{% set python_min = '3.10' %}
{% set name = "pywatershed" %}
{% set version = "2.0.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pywatershed-{{ version }}.tar.gz
  sha256: 334b69f88fd876858125358d1bf96550d17867332001e98d3dbb1f3171e032db

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - importlib-metadata
    - numpy
    - twine
    - pip
  run:
    - cartopy
    - click !=8.1.0
    - dataretrieval
    - contextily
    - epiweeks4cf
    - filelock
    - flopy
    - folium
    - geopandas
    - geoviews
    - git
    - holoviews
    - hvplot
    - ipython
    - ipywidgets
    - jupyter
    - jupyter-black
    - jupyterlab
    - nbconvert
    - netCDF4
    - networkx
    - numpy >=2.0.0
    - numba
    - modflow-devtools
    - pandas >=1.4.0
    - pint
    - pip
    - pre-commit
    - pydot
    - pytest !=8.1.0
    - pytest-cov
    - pytest-env
    - pytest-order
    - pytest-xdist
    - python >={{ python_min }},<3.12
    - pyyaml
    - ruff
    - shapely
    - sphinx
    - sphinx-book-theme >=0.3.3
    - sphinx-autodoc-typehints >=2.2.1
    - sphinx-autosummary-accessors
    - sphinx-copybutton
    - tqdm
    - xarray >=2024.06.0
    - xmltodict

test:
  imports:
    - pywatershed
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://github.com/EC-USGS/pywatershed
  summary: pywatershed is a Python package for hydrologic modeling
  license: CC0-1.0
  license_file: LICENSE
  doc_url: https://pywatershed.readthedocs.io
  dev_url: https://github.com/EC-USGS/pywatershed

extra:
  recipe-maintainers:
    - jmccreight
    - wpbonelli
